require('core-js/fn/array/find')
require('core-js/fn/array/find-index')
require('core-js/fn/array/includes')
require('core-js/fn/object/assign')
require('core-js/fn/object/keys')
require('core-js/fn/object/values')
require('core-js/fn/function/bind')
require('core-js/fn/symbol/iterator')
